routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if (request()->getHost() === env('TENANT_DOMAIN'))
{
    Route::post('/', 'LandlordController@signUp')->name('landlord.sign-up');
    Route::get('/success', 'LandlordController@success')->name('landlord.success');

    Route::view('/docs/initial-setup', 'landlord.static.docs.initial-setup')->name('landlord.docs.initial-setup');
    Route::view('/docs/workflow', 'landlord.static.docs.workflow')->name('landlord.docs.workflow');
    Route::view('/docs', 'landlord.static.docs')->name('landlord.docs');

    Route::view('/', 'landlord.static.homepage')->name('landlord.static.homepage');
} else {
    Auth::routes();

    Route::group(['middleware' => ['auth']], function () 
    {
        // These routes need to be accessible in the initial setup and generally. 
        Route::get('/location/ajax/create/{parentID}/{title}', 'LocationController@ajaxCreate')->name('location.ajax-create')->middleware('check.permission:location.admin');
        Route::get('/location/ajax/delete/{id}', 'LocationController@ajaxDelete')->name('location.ajax-delete')->middleware('check.permission:location.admin');
        Route::get('/location/ajax/is-rentable/{id}/{trueOrFalse}', 'LocationController@ajaxIsRentable')->name('location.ajax-is-rentable')->middleware('check.permission:location.admin');
        Route::get('/location/ajax/update/{id}/{title}', 'LocationController@ajaxUpdate')->name('location.ajax-update')->middleware('check.permission:location.admin');
        Route::get('/location/json', 'LocationController@json')->name('location.json')->middleware('check.permission:location.admin');

        Route::group(['middleware' => ['initial.setup.lock']], function () 
        {
            Route::get('/initial-setup', 'InitialSetupController@start')->name('initial-setup');
            Route::get('/initial-setup/location', 'InitialSetupController@location')->name('initial-setup.location');
            Route::get('/initial-setup/resident', 'InitialSetupController@resident')->name('initial-setup.resident');
            Route::get('/initial-setup/staff', 'InitialSetupController@staff')->name('initial-setup.staff');
            Route::post('/initial-setup/location', 'InitialSetupController@locationPost')->name('initial-setup.location-post');
            Route::post('/initial-setup/resident', 'InitialSetupController@residentPost')->name('initial-setup.resident-post');
            Route::post('/initial-setup/staff', 'InitialSetupController@staffPost')->name('initial-setup.staff-post');
        });
        
        Route::group(['middleware' => ['initial.setup']], function () 
        {
            // Route::get('/session/appointment/{redirectRoute?}', 'SessionController@appointment')->name('session.appointment');
            // Route::post('/session/appointment', 'SessionController@appointmentPost')->name('session.appointment-post');
            // Route::get('/session/appointmentCheck/{redirectRoute?}', 'SessionController@appointmentCheck')->name('session.appointment-check');
            
            // Route::get('/appointment/mine/{id}', 'AppointmentController@mine')->name('appointment.mine');
            // Route::get('/appointment/mine', 'AppointmentController@mineAll')->name('appointment.mineall');
            // Route::get('/appointment/create', 'AppointmentController@create')->name('appointment.create');
            // Route::post('/appointment/create', 'AppointmentController@createPost')->name('appointment.create-post');
            // Route::get('/appointment/{id}/edit', 'AppointmentController@edit')->name('appointment.edit');
            // Route::get('/appointment/{id}', 'AppointmentController@show')->name('appointment.show');
            // Route::get('/appointment', 'AppointmentController@index')->name('appointment.index');

            Route::get('/care-home/resident/falls-assessment/{id}', 'CareHome\ResidentController@fallsAssessment')->name('care-home.resident.falls-assessment.view')->middleware('check.permission:resident.read');
            Route::get('/care-home/resident/create', 'CareHome\ResidentController@create')->name('care-home.resident.create')->middleware('check.permission:resident.create');
            Route::post('/care-home/resident/create', 'CareHome\ResidentController@createPost')->name('care-home.resident.create-post')->middleware('check.permission:resident.create');
            Route::get('/care-home/resident/{id}/edit/{page?}', 'CareHome\ResidentController@edit')->name('care-home.resident.edit')->middleware('check.permission:resident.edit');
            Route::post('/care-home/resident/{id}/edit', 'CareHome\ResidentController@editPost')->name('care-home.resident.edit-post')->middleware('check.permission:resident.edit');
            Route::get('/care-home/resident/{id}/finance/{page?}', 'CareHome\ResidentController@finance')->name('care-home.resident.finance')->middleware('check.permission:resident.edit');
            Route::post('/care-home/resident/{id}/finance', 'CareHome\ResidentController@financePost')->name('care-home.resident.finance-post')->middleware('check.permission:resident.edit');
            Route::get('/care-home/resident/{id}', 'CareHome\ResidentController@show')->name('care-home.resident.show')->middleware('check.permission:resident.read');
            Route::get('/care-home/resident/historic', 'CareHome\ResidentController@historic')->name('care-home.resident.historic')->middleware('check.permission:resident.read');
            Route::get('/care-home/resident', 'CareHome\ResidentController@index')->name('care-home.resident.index')->middleware('check.permission:resident.read');

            Route::get('/company', 'CompanyController@index')->name('company.index')->middleware('check.permission:company.admin');
            Route::post('/company', 'CompanyController@indexPost')->name('company.index-post')->middleware('check.permission:company.admin');

            // Route::get('/contact', 'ContactController@contact')->name('contact');

            Route::get('/complaint/create', 'ComplaintController@create')->name('complaint.create')->middleware('check.permission:complaint.create');
            Route::post('/complaint/create', 'ComplaintController@createPost')->name('complaint.create-post')->middleware('check.permission:complaint.create');
            Route::get('/complaint/mine', 'ComplaintController@mine')->name('complaint.mine')->middleware('check.permission:complaint.mine');
            Route::get('/complaint/{id}/edit', 'ComplaintController@edit')->name('complaint.edit')->middleware('check.permission:complaint.edit');
            Route::post('/complaint/{id}/edit', 'ComplaintController@editPost')->name('complaint.edit-post')->middleware('check.permission:complaint.edit');
            Route::get('/complaint/{id}', 'ComplaintController@show')->name('complaint.show')->middleware('check.permission:complaint.read');
            Route::get('/complaint', 'ComplaintController@index')->name('complaint.index')->middleware('check.permission:complaint.read');

            Route::get('/cost-code/create', 'CostCodeController@create')->name('cost-code.create');
            Route::post('/cost-code/create', 'CostCodeController@createPost')->name('cost-code.create-post');
            Route::get('/cost-code/{id}/edit', 'CostCodeController@edit')->name('cost-code.edit');
            Route::post('/cost-code/{id}/edit', 'CostCodeController@editPost')->name('cost-code.edit-post');
            Route::get('/cost-code/{id}', 'CostCodeController@show')->name('cost-code.show');
            Route::get('/cost-code', 'CostCodeController@index')->name('cost-code.index');

            Route::get('/customer/create', 'CustomerController@create')->name('customer.create')->middleware('check.permission:customer.create');
            Route::post('/customer/create', 'CustomerController@createPost')->name('customer.create-post')->middleware('check.permission:customer.create');
            Route::get('/customer/{id}/edit', 'CustomerController@edit')->name('customer.edit')->middleware('check.permission:customer.edit');
            Route::post('/customer/{id}/edit', 'CustomerController@editPost')->name('customer.edit-post')->middleware('check.permission:customer.edit');
            Route::get('/customer/{id}', 'CustomerController@show')->name('customer.show')->middleware('check.permission:customer.read');
            Route::get('/customer', 'CustomerController@index')->name('customer.index')->middleware('check.permission:customer.read');
            
            Route::post('/health-and-safety-incident/{id}/injury/{injuryID}/edit', 'HealthAndSafetyController@editInjuryPost')->name('health-and-safety-incident.edit-injury-post')->middleware('check.permission:health-and-safety-incident.edit-injury-post');
            Route::post('/health-and-safety-incident/{id}/injury/create', 'HealthAndSafetyController@createInjuryPost')->name('health-and-safety-incident.create-injury-post')->middleware('check.permission:health-and-safety-incident.create-injury-post');
            Route::get('/health-and-safety-incident/{id}/injury/{injuryID}/edit', 'HealthAndSafetyController@editInjury')->name('health-and-safety-incident.edit-injury')->middleware('check.permission:health-and-safety-incident.edit-injury');
            Route::get('/health-and-safety-incident/{id}/injury/create', 'HealthAndSafetyController@createInjury')->name('health-and-safety-incident.create-injury')->middleware('check.permission:health-and-safety-incident.create-injury');

app/Models/CareHome/Assessment/Fall.php
<?php

namespace App\Models\CareHome\Assessment;

use App\Models\BaseModel;
use App\Traits\CareHomeAssessment;
use Illuminate\Database\Eloquent\SoftDeletes;

class Fall extends BaseModel
{
    use CareHomeAssessment;
    use SoftDeletes;

    protected $fillable = ['resident_id', 'date_of_assessment', 'completed_by_user_id', 'json_response'];
    protected $table = 'care_home_records_falls_risk_assessments';
    public $timestamps = true;

    protected $dates = ['deleted_at'];

    public function getNumberOfRiskFactorsAttribute(): int
    {
        $questions = self::questionsWithoutCategories();
        $score     = 0;
        $answers   = $this->jsonAsArray();

        foreach (array_keys($questions) as $key)
        {
            if ($answers[$key])
            {
                $score++;
            }
        }

        return $score;
    }

    public function jsonAsArray(): array
    {
        return json_decode($this->json_response, true);
    }

    public static function questions(): array
    {
        return [
            'History and Health' => [
                'previous_falls' => 'Has the resident had more than one fall in the last 12 months?',
                'osteoporosis' => 'Does the resident have, or are they at risk of osteoporosis?',
                'confused' => 'Is the resident confused, disorientated, restless or agitated?',
                'judgement' => 'Does the resident have reduced judgement and/or are they uncorporative with staff frequently?',
                'continence' => 'Does the resident have continence issues that could increase risk of falls?',
            ],
            'Balance and Mobility' => [
                'unsteady' => 'Is the resident unsteady on their feet or unsafe walking?',
                'transfers' => 'Does the resident have difficulty with getting on and off the toilet, bed, chair or similar?',
                'dizziness' => 'Does the resident suffer from dizziness, light-headedness when standing, fainting or palpitations?',
            ],
            'Medication' => [
                'four_or_more' => 'Is the patient on four or more different types of medication?',
                'risky_medicines' => 'Is the patient taking sedatives, anti-depressents, anti-Parkinson medication, diuretics, anti-psychotics, anti-coagulants or anti-hypertensives?',
                'recent_change' => 'Has there been a recent change in medication that might affect falls?',
            ],
            'Nutrition' => [
                'lost_weight' => 'Has the patient lost weight recently and/or do they have little appetite?',
                'daylight' => 'Does the patient spend little time outside in the sun?',
            ],
            'Senses' => [
                'bad_eyesight' => 'Does the resident have bad eyesight?',
                'bad_hearing' => 'Does the resident have bad hearing?',
            ],
            'Clothing' => [
                'feet_issues' => 'Does the resident have corns, ingrown nails, bunions, loss of sense, or similar foot problems?',
                'bad_shoes' => 'Does the resident wear poorly fitting shoes, or those that are difficult to walk in?',
            ],
            'Other' => [
                'out_of_bed' => 'Does the resident get out of bed regularly overnight?',
                'new_resident' => 'Is the resident new, and if so, are they well oriented to their new environment?',
                'other' => 'Are there any other factors that might increase the risk of falls?',
            ],
        ];
    }

    public static function questionsWithoutCategories(): array
    {
        $questionsWithCategories    = self::questions();
        $questionsWithoutCategories = [];

        foreach ($questionsWithCategories as $question)
        {
            foreach ($question as $key => $text)
            {
                $questionsWithoutCategories[$key] = $text;
            }
        }

        return $questionsWithoutCategories;
    }
}

app/Models/CareHome/Assessment/Malnutrition.php
<?php

namespace App\Models\CareHome\Assessment;

use App\Models\BaseModel;
use App\Traits\CareHomeAssessment;
use Illuminate\Database\Eloquent\SoftDeletes;

class Malnutrition extends BaseModel
{
    use CareHomeAssessment;
    use SoftDeletes;

    protected $fillable = ['resident_id', 'date_of_assessment', 'completed_by_user_id', 'bmi', 'weight_loss', 'is_acutely_ill', 'additional_comments'];
    protected $table = 'care_home_records_malnutrition_assessments';
    public $timestamps = true;

    protected $dates = ['deleted_at'];

    public function getAcutelyIllFormattedAttribute(): string
    {
        if ($this->is_acutely_ill)
        {
            return 'Y';
        }

        return 'N';
    }

    public function getBmiFormattedAttribute(): string
    {
        $return = [
            0 => '> 20',
            1 => '18.5 - 20',
            2 => '< 18.5',
        ];

        return $return[$this->must_bmi];
    }

    public function getRiskFormattedAttribute(): string
    {
        if ($this->riskScore() === 0)
        {
            return 'Low';
        } elseif ($this->riskScore() === 1) {
            return 'Medium';
        }

        return 'High';
    }

    public function getWeightLossFormattedAttribute(): string
    {
        $return = [
            0 => '< 5%',
            1 => '5% - 10%',
            2 => '> 10%',
        ];

        return $return[$this->must_weight_loss];
    }

    public function riskScore(): int
    {
        return $this->must_bmi + $this->must_weight_loss + $this->is_acutely_ill * 2;
    }
}

app/Models/CareHome/Assessment/Skin.php
<?php

namespace App\Models\CareHome\Assessment;

use App\Models\BaseModel;
use App\Traits\CareHomeAssessment;
use Illuminate\Database\Eloquent\SoftDeletes;

class Skin extends BaseModel
{
    use CareHomeAssessment;
    use SoftDeletes;

    protected $fillable = ['resident_id', 'date_of_assessment', 'completed_by_user_id', 'braden_sensory_perception', 'braden_moisture', 'braden_activity', 'braden_mobility', 'braden_nutrition', 'braden_friction', 'braden_total', 'general_observations', 'is_broken_skin', 'is_infection_present', 'infection_treated_with'];
    protected $table = 'care_home_records_skin_integrity_assessments';
    public $timestamps = true;

    protected $dates = ['deleted_at'];

    public function getButtonClassAttribute(): string
    {
        if ($this->braden_total <= 12)
        {
            return 'btn btn-danger';
        } elseif ($this->braden_total <= 14) {
            return 'btn btn-warning';
        }

        return 'btn btn-success';
    }

    public function getButtonTextAttribute(): string
    {
        if ($this->braden_total <= 12)
        {
            return 'High Risk';
        } elseif ($this->braden_total <= 14) {
            return 'Medium Risk';
        }

        return 'Low Risk';
    }

    public function getBrokenSkinFormattedAttribute(): string
    {
        if ($this->is_broken_skin)
        {
            return 'Y';
        }

        return 'N';
    }

    public function getInfectionPresentFormattedAttribute(): string
    {
        if ($this->is_infection_present)
        {
            return 'Y';
        }

        return 'N';
    }
}

app/Models/CareHome/CareRecord/Catheter.php
<?php

namespace App\Models\CareHome\CareRecord;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;

class Catheter extends BaseModel
{
    use SoftDeletes;

    protected $fillable = ['resident_id', 'date_of_assessment', 'completed_by_user_id', 'date_changed', 'reasons', 'size', 'changed_by_user_id'];
    protected $table = 'care_home_records_catheters';
    public $timestamps = true;

    protected $dates = ['deleted_at'];

    public function changedByUser(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\Models\User', 'changed_by_user_id');
    }
}

resources/views/care-home/resident/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Resident')

@section('content_header')
    <h1>Create Resident</h1>
@stop

@section('content')
    {{ Form::open(['route' => 'care-home.resident.create-post', 'method' => 'post']) }}
        <div class="row">
            <div class="col-md-12 col-lg-6">
                <div class="card card-dark">
                    <div class="card-header">User Details</div>
                    <div class="card-body">
                        {{ Form::bsText('Name', 'name', null, ['helpBlock' => 'This is the full name of the user, "Mr. John Smith", for example.']) }}
                        {{ Form::bsText('Preferred Name', 'preferred_name', null, ['helpBlock' => 'This is the name the person preferrs to be addressed by, which could be "Mr. Smith", "John", "Johnny", etc.']) }}
                        {{ Form::bsText('First Name', 'first_name') }}
                        {{ Form::bsText('Middle Names', 'middle_names') }}
                        {{ Form::bsText('Last Name', 'last_name') }}
                        {{ Form::bsFile('Picture (optional)', 'picture_path') }}
                        {{ Form::hidden('is_customer', 1) }}
                        {{ Form::bsSelect('Ethnic Origin', 'ethnic_origin_id', $ethnicOrigins, null, ['placeholder' => '']) }}
                        {{ Form::bsSelect('Religion', 'religion_id', $religions, null, ['placeholder' => '']) }}
                        {{ Form::bsSelect('Sexual Orientation', 'sexual_orientation_id', $sexualOrientations, null, ['placeholder' => '']) }}
                    </div>
                </div>
            </div>

            <div class="col-md-12 col-lg-6">
                <div class="card card-dark">
                    <div class="card-header">Address and Contact Information</div>
                    <div class="card-body">
                        {{ Form::bsText('Address Line 1', 'address_1') }}
                        {{ Form::bsText('Address Line 2', 'address_2') }}
                        {{ Form::bsText('Address Line 3', 'address_3') }}
                        {{ Form::bsText('Address Line 4', 'address_4') }}
                        {{ Form::bsSelect('County', 'county_id', $counties, null, ['placeholder' => '']) }}
                        {{ Form::bsText('Phone Number', 'phone_number') }}
                        {{ Form::bsText('Mobile Number', 'mobile_number') }}
                    </div>
                </div>
            </div>

            <div class="col-12">
                <div class="card card-dark">
                    <div class="card-header">Update or Set Billing Information</div>
                    <div class="card-body">
                        {{ Form::bsSelect('Room', 'rented_thing_id', $rooms, null, ['placeholder' => '']) }}
                        {{ Form::bsDate('Effective Date', 'from_date') }}
                    </div>
                </div>
            </div>
        </div>

        {{ Form::bsSubmit('Create User') }}
    {{ Form::close() }}
@endsection

resources/views/care-home/resident/falls.blade.php
@extends('adminlte::page')

@section('title', 'Falls Assessment')

@section('content_header')
    <h1>Falls Assessment</h1>
@stop

@section('content')
    <p>This is an assessment of <a href="{{ route('care-home.resident.show', $assessment->resident->id) }}">{{ $assessment->resident->user->name }}</a> made on {{ $assessment->created_at }} by {{ $assessment->user->name }}.</p>

    <div class="card card-dark">
        <div class="card-header">Assessment</div>
        <div class="card-body">
            <div class="row">
                @foreach ($quesWithCat as $category => $questions)
                    <div class="col-12"><b>{{ $category }}</b></div>
                    
                    @foreach ($questions as $key => $text)
                        <div class="col-2">
                            @if ($answers[$key])
                                <span style="color:#72b01d"><i class="fas fa-check"></i></span>
                            @else
                                <span style="color:#bf0603"><i class="fas fa-times"></i></span>
                            @endif
                        </div>
                        <div class="col-10">{{ $text }}</div>

                        @if ($answers[$key.'_comments'])
                            <div class="col-1">&nbsp;</div>
                            <div class="col-1">Notes</div>
                            <div class="col-10"><i>{{ $answers[$key.'_comments'] }}</i></div>
                        @endif
                    @endforeach

                    <div class="col-12">&nbsp;</div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/care-home/resident/finance.blade.php
@extends('adminlte::page')

@section('plugins.Select2', true)

@section('title', 'Resident Finance Details')

@section('content_header')
    <h1>Resident Finance Details</h1>
@stop

@section('content')
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link @if ($page ==='stay') active @endif" id="stay-tab" data-toggle="tab" href="#stay" role="tab" aria-controls="stay" aria-selected="true">Stays</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if ($page ==='invoice') active @endif" id="invoice-tab" id="invoice-tab" data-toggle="tab" href="#invoice" role="tab" aria-controls="invoice" aria-selected="false">Invoices</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if ($page ==='funding') active @endif" id="funding-tab" id="funding-tab" data-toggle="tab" href="#funding" role="tab" aria-controls="funding" aria-selected="false">Funding</a>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade @if ($page ==='stay') show active @endif" id="stay" role="tabpanel" aria-labelledby="stay-tab">@include('care-home.resident.finance-component.stay')</div>
        <div class="tab-pane fade @if ($page ==='invoice') show active @endif" id="invoice" role="tabpanel" aria-labelledby="invoice-tab">@include('care-home.resident.finance-component.invoice')</div>
        <div class="tab-pane fade @if ($page ==='funding') show active @endif" id="funding" role="tabpanel" aria-labelledby="funding-tab">@include('care-home.resident.finance-component.funding')</div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function() {
            $('select[name="responsible_user_id[0]"]').select2();
            $('select[name="responsible_user_id[1]"]').select2();
            $('select[name="responsible_user_id[2]"]').select2();
            $('select[name="responsible_user_id[3]"]').select2();
            $('select[name="responsible_user_id[4]"]').select2();
            $('select[name="responsible_user_id[5]"]').select2();
            $('select[name="responsible_user_id[6]"]').select2();
            $('select[name="responsible_user_id[7]"]').select2();
            $('select[name="responsible_user_id[8]"]').select2();
            $('select[name="responsible_user_id[9]"]').select2();
        });
    </script>
@endsection

resources/views/care-home/resident/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Resident')

@section('content_header')
    <h1>{{ $resident->user->name }} - 
        @if ($rental)
            {{ $rental->rentedThing->name }}
        @else
            Former Resident
        @endif</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card card-dark">
                <div class="card-header">Resident Details</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12"><img src="{{ $resident->user->picture_url }}" style="border-radius: 50%; max-width: 100%; height: auto;" alt="Resident Image" class="img-fluid"></div>
                        <div class="col-12">
                            {{ $resident->user->name }}
                            @if ($resident->user->preferred_name)
                                ({{ $resident->user->preferred_name }})
                            @endif
                        </div>
                        <div class="col-12">&nbsp;</div>
                        <div class="col-1"><i class="fas fa-at"></i></div><div class="col-11">{{ $resident->user->email }}</div>
                        <div class="col-1"><i class="fas fa-home"></i></div><div class="col-11">{!! $resident->user->address !!}</div>
                        <div class="col-1"><i class="fas fa-phone"></i></div><div class="col-11">{{ $resident->user->phone_number }}</div>
                        <div class="col-1"><i class="fas fa-mobile-alt"></i></div><div class="col-11">{{ $resident->user->mobile_number }}</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-sm-6 col-md-8">
            <div class="card card-dark">
                <div class="card-header">Critical Information</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            @if ($resident->is_challenging)
                                <h3><i class="fas fa-exclamation-triangle"></i> Challenging Behaviour</h3>

                                <p>{!! nl2br($resident->challenging_details) !!}</p>
                            @endif

                            @if ($resident->is_safeguarding)
                                <h3><i class="fas fa-exclamation-triangle"></i> Safeguarding Risks</h3>

                                <p>{!! nl2br($resident->safeguarding_details) !!}</p>
                            @endif

                            @if ($resident->allergies)
                                <h3><i class="fas fa-exclamation-triangle"></i> Allergies</h3>

                                <p>{!! nl2br($resident->allergies) !!}</p>
                            @endif

                            <div class="row">
                                <div class="col-12 col-sm-4">
                                    <h3>GP Details</h3>
                                    <p>{!! nl2br($resident->gp_details) !!}</p>
                                </div>
                                <div class="col-12 col-sm-4">
                                    <h3>Next of Kin</h3>
                                    <p>{!! nl2br($resident->next_of_kin) !!}</p>
                                </div>
                                <div class="col-12 col-sm-4">
                                    <h3>Power of Attorney</h3>
                                    <p>{!! nl2br($resident->power_of_attorney) !!}</p>
                                </div>

                                <div class="col-12">
                                    @if ($eolWishes)
                                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#eolModal">
                                            View End of Life Wishes
                                        </button>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card card-dark">
                <div class="card-header">Other Risks and Hazards</div>
                <div class="card-body">
                    @if (!$eolWishes)
                        <div class="alert alert-danger">There is no information for end of life wishes for this resident. Please <a href="{{ route('care-home.resident.edit', [$resident->id, 'end-of-life']) }}">ensure these are recorded</a> as soon as possible.</div>
                    @endif

                    @if (!$fallAssess)
                        <div class="alert alert-danger">No Falls Assessments have been completed. Please ensure that a qualified member of staff <a href="{{ route('care-home.resident.edit', [$resident->id, 'falls']) }}">completes a fall assessment</a> as soon as possible.</div>
                    @else
                        <h3>Falls</h3>
                        @if ($fallAssess->number_of_risk_factors == 0)
                            <div class="alert alert-success">On the most recent falls risk assessment (completed on {{ $fallAssess->date_created }}), no risk factors were identified.
                        @else
                            <p>{{ $fallAssess->number_of_risk_factors }} risk factors have been identified in the falls risk. 
                        @endif

                        <p>For more information, <a href="{{ route('care-home.resident.falls-assessment.view', $fallAssess->id) }}">view the full risk assessment</a>.</p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="eolModal" tabindex="-1" role="dialog" aria-labelledby="eolModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="eolModalLabel">End of Life Wishes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (!$eolWishes)

                    @else 

                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection